FROM centos/httpd

RUN echo "multilib_policy=best" >> /etc/yum.conf
RUN yum  -y update && \
    yum install -y \
                   gcc-c++ \
                   git \
                   xinetd \
                   perl \
                   curl \
                   python \
                   openssh-server \
                   openssh-clients \
                   expect \
                   man \
                   python-argparse \
                   sshpass \
                   wget \
                   make \
                   cmake \
                   dos2unix \
                   which \
                   file \
                   unzip \
                   lsof \
                   net-tools \
                   java-devel \
                   libicu \
                   libicu-devel \
                   recode \
                   bzip2 \
                   httpd \
                   php \
                   || true && \
    yum install -y http://libslack.org/daemon/download/daemon-0.6.4-1.i686.rpm > /dev/null && \
    package-cleanup --cleandupes && \
    yum  -y clean all && \
    rm -rf /var/cache/yum

RUN ssh-keygen -f /etc/ssh/ssh_host_rsa_key -N '' -t rsa && \
    ssh-keygen -f /etc/ssh/ssh_host_dsa_key -N '' -t dsa && \
    ssh-keygen -t ecdsa -N "" -f /etc/ssh/ssh_host_ecdsa_key && \
    ssh-keygen -t ed25519 -N "" -f /etc/ssh/ssh_host_ed25519_key && \
    sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd && \
    echo 'root:docker' | chpasswd
RUN cd /var/www/html && \
    git clone git://github.com/OSEHRA-Sandbox/SyntheaPatientViz.git synthea && \
    cd synthea && \
    mkdir local

EXPOSE 22 8080
